// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SP_Common.txt

#ifndef PROTOBUF_SP_5fCommon_2etxt__INCLUDED
#define PROTOBUF_SP_5fCommon_2etxt__INCLUDED

#ifdef _MSC_VER
#  pragma warning(push)
#  pragma warning(disable: 4127 4244 4267 4996)
#endif

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_SP_5fCommon_2etxt();
void protobuf_AssignDesc_SP_5fCommon_2etxt();
void protobuf_ShutdownFile_SP_5fCommon_2etxt();

class GM_MessageStatiData;
class GM_MessageStatistics;

// ===================================================================

class GM_MessageStatiData : public ::google::protobuf::Message {
 public:
  GM_MessageStatiData();
  virtual ~GM_MessageStatiData();

  GM_MessageStatiData(const GM_MessageStatiData& from);

  inline GM_MessageStatiData& operator=(const GM_MessageStatiData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GM_MessageStatiData& default_instance();

  void Swap(GM_MessageStatiData* other);

  // implements Message ----------------------------------------------

  GM_MessageStatiData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GM_MessageStatiData& from);
  void MergeFrom(const GM_MessageStatiData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 message_id = 1;
  inline bool has_message_id() const;
  inline void clear_message_id();
  static const int kMessageIdFieldNumber = 1;
  inline ::google::protobuf::int32 message_id() const;
  inline void set_message_id(::google::protobuf::int32 value);

  // required int32 receive_count = 2;
  inline bool has_receive_count() const;
  inline void clear_receive_count();
  static const int kReceiveCountFieldNumber = 2;
  inline ::google::protobuf::int32 receive_count() const;
  inline void set_receive_count(::google::protobuf::int32 value);

  // required float total_use_time = 3;
  inline bool has_total_use_time() const;
  inline void clear_total_use_time();
  static const int kTotalUseTimeFieldNumber = 3;
  inline float total_use_time() const;
  inline void set_total_use_time(float value);

  // required float max_use_time = 4;
  inline bool has_max_use_time() const;
  inline void clear_max_use_time();
  static const int kMaxUseTimeFieldNumber = 4;
  inline float max_use_time() const;
  inline void set_max_use_time(float value);

  // required int32 record_time = 5;
  inline bool has_record_time() const;
  inline void clear_record_time();
  static const int kRecordTimeFieldNumber = 5;
  inline ::google::protobuf::int32 record_time() const;
  inline void set_record_time(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GM_MessageStatiData)
 private:
  inline void set_has_message_id();
  inline void clear_has_message_id();
  inline void set_has_receive_count();
  inline void clear_has_receive_count();
  inline void set_has_total_use_time();
  inline void clear_has_total_use_time();
  inline void set_has_max_use_time();
  inline void clear_has_max_use_time();
  inline void set_has_record_time();
  inline void clear_has_record_time();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 message_id_;
  ::google::protobuf::int32 receive_count_;
  float total_use_time_;
  float max_use_time_;
  ::google::protobuf::int32 record_time_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_SP_5fCommon_2etxt();
  friend void protobuf_AssignDesc_SP_5fCommon_2etxt();
  friend void protobuf_ShutdownFile_SP_5fCommon_2etxt();

  void InitAsDefaultInstance();
  static GM_MessageStatiData* default_instance_;
};
// -------------------------------------------------------------------

class GM_MessageStatistics : public ::google::protobuf::Message {
 public:
  GM_MessageStatistics();
  virtual ~GM_MessageStatistics();

  GM_MessageStatistics(const GM_MessageStatistics& from);

  inline GM_MessageStatistics& operator=(const GM_MessageStatistics& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GM_MessageStatistics& default_instance();

  void Swap(GM_MessageStatistics* other);

  // implements Message ----------------------------------------------

  GM_MessageStatistics* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GM_MessageStatistics& from);
  void MergeFrom(const GM_MessageStatistics& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 count = 1;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 1;
  inline ::google::protobuf::int32 count() const;
  inline void set_count(::google::protobuf::int32 value);

  // repeated .GM_MessageStatiData datalist = 2;
  inline int datalist_size() const;
  inline void clear_datalist();
  static const int kDatalistFieldNumber = 2;
  inline const ::GM_MessageStatiData& datalist(int index) const;
  inline ::GM_MessageStatiData* mutable_datalist(int index);
  inline ::GM_MessageStatiData* add_datalist();
  inline const ::google::protobuf::RepeatedPtrField< ::GM_MessageStatiData >&
      datalist() const;
  inline ::google::protobuf::RepeatedPtrField< ::GM_MessageStatiData >*
      mutable_datalist();

  // @@protoc_insertion_point(class_scope:GM_MessageStatistics)
 private:
  inline void set_has_count();
  inline void clear_has_count();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::GM_MessageStatiData > datalist_;
  ::google::protobuf::int32 count_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_SP_5fCommon_2etxt();
  friend void protobuf_AssignDesc_SP_5fCommon_2etxt();
  friend void protobuf_ShutdownFile_SP_5fCommon_2etxt();

  void InitAsDefaultInstance();
  static GM_MessageStatistics* default_instance_;
};
// ===================================================================


// ===================================================================

// GM_MessageStatiData

// required int32 message_id = 1;
inline bool GM_MessageStatiData::has_message_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GM_MessageStatiData::set_has_message_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GM_MessageStatiData::clear_has_message_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GM_MessageStatiData::clear_message_id() {
  message_id_ = 0;
  clear_has_message_id();
}
inline ::google::protobuf::int32 GM_MessageStatiData::message_id() const {
  return message_id_;
}
inline void GM_MessageStatiData::set_message_id(::google::protobuf::int32 value) {
  set_has_message_id();
  message_id_ = value;
}

// required int32 receive_count = 2;
inline bool GM_MessageStatiData::has_receive_count() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GM_MessageStatiData::set_has_receive_count() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GM_MessageStatiData::clear_has_receive_count() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GM_MessageStatiData::clear_receive_count() {
  receive_count_ = 0;
  clear_has_receive_count();
}
inline ::google::protobuf::int32 GM_MessageStatiData::receive_count() const {
  return receive_count_;
}
inline void GM_MessageStatiData::set_receive_count(::google::protobuf::int32 value) {
  set_has_receive_count();
  receive_count_ = value;
}

// required float total_use_time = 3;
inline bool GM_MessageStatiData::has_total_use_time() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GM_MessageStatiData::set_has_total_use_time() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GM_MessageStatiData::clear_has_total_use_time() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GM_MessageStatiData::clear_total_use_time() {
  total_use_time_ = 0;
  clear_has_total_use_time();
}
inline float GM_MessageStatiData::total_use_time() const {
  return total_use_time_;
}
inline void GM_MessageStatiData::set_total_use_time(float value) {
  set_has_total_use_time();
  total_use_time_ = value;
}

// required float max_use_time = 4;
inline bool GM_MessageStatiData::has_max_use_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GM_MessageStatiData::set_has_max_use_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GM_MessageStatiData::clear_has_max_use_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GM_MessageStatiData::clear_max_use_time() {
  max_use_time_ = 0;
  clear_has_max_use_time();
}
inline float GM_MessageStatiData::max_use_time() const {
  return max_use_time_;
}
inline void GM_MessageStatiData::set_max_use_time(float value) {
  set_has_max_use_time();
  max_use_time_ = value;
}

// required int32 record_time = 5;
inline bool GM_MessageStatiData::has_record_time() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GM_MessageStatiData::set_has_record_time() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GM_MessageStatiData::clear_has_record_time() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GM_MessageStatiData::clear_record_time() {
  record_time_ = 0;
  clear_has_record_time();
}
inline ::google::protobuf::int32 GM_MessageStatiData::record_time() const {
  return record_time_;
}
inline void GM_MessageStatiData::set_record_time(::google::protobuf::int32 value) {
  set_has_record_time();
  record_time_ = value;
}

// -------------------------------------------------------------------

// GM_MessageStatistics

// required int32 count = 1;
inline bool GM_MessageStatistics::has_count() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GM_MessageStatistics::set_has_count() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GM_MessageStatistics::clear_has_count() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GM_MessageStatistics::clear_count() {
  count_ = 0;
  clear_has_count();
}
inline ::google::protobuf::int32 GM_MessageStatistics::count() const {
  return count_;
}
inline void GM_MessageStatistics::set_count(::google::protobuf::int32 value) {
  set_has_count();
  count_ = value;
}

// repeated .GM_MessageStatiData datalist = 2;
inline int GM_MessageStatistics::datalist_size() const {
  return datalist_.size();
}
inline void GM_MessageStatistics::clear_datalist() {
  datalist_.Clear();
}
inline const ::GM_MessageStatiData& GM_MessageStatistics::datalist(int index) const {
  return datalist_.Get(index);
}
inline ::GM_MessageStatiData* GM_MessageStatistics::mutable_datalist(int index) {
  return datalist_.Mutable(index);
}
inline ::GM_MessageStatiData* GM_MessageStatistics::add_datalist() {
  return datalist_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::GM_MessageStatiData >&
GM_MessageStatistics::datalist() const {
  return datalist_;
}
inline ::google::protobuf::RepeatedPtrField< ::GM_MessageStatiData >*
GM_MessageStatistics::mutable_datalist() {
  return &datalist_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#ifdef _MSC_VER
#  pragma warning(pop)
#endif

#endif  // PROTOBUF_SP_5fCommon_2etxt__INCLUDED
